version: "3.8"
services:
  r_studio_docker_compose:
    image: rocker/rstudio
    environment:
      - ADD=shiny
      - PASSWORD=****
    volumes:
      - .:/home/rstudio
    ports:
      - "3838:3838"
      - "8787:8787"
