version: "3.8"
services:
  r_studio_docker_compose:
    env_file:
     - rocker.env
    image: rocker/rstudio
    volumes:
      - .:/home/rstudio
    ports:
      - "3838:3838"
      - "8787:8787"
